---

##
##  ----------------------------------------------------------------
## Copyright 2017 Cisco Systems
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##    http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ------------------------------------------------------------------
##
## Author:  Fabrizio Maccioni, fabrimac@cisco.com
##
## This software is for demonstration purposes only and is not supported
## by Cisco systems.
##

- name: test Ansible ios_banner module on Cisco IOS XE
  hosts: ios-xe !cat4500-X
  gather_facts: no

  tasks:
    - name: configure login banner
      ios_banner:
        banner: login
        text: |
          ***************************************************************************

                 ||        ||
                 ||        ||             Cisco Systems, Inc.
                ||||      ||||            TME Lab
            ..:||||||:..:||||||:..        SJC23/1/163

                                      NOTICE TO USERS

          UNAUTHORIZED ACCESS TO THIS NETWORK DEVICE IS PROHIBITED.
          You must have explicit permission to access or configure this
          device.  All activities performed on this device are logged and
          violations of this policy may result in disciplinary action.

          ***************************************************************************
